# Generated by Django 5.0.6 on 2026-09-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='excluido_em',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
